site_name: Виктория Водовозова | Портфолио
site_url: https://viktoriavodovozova.github.io
repo_url: https://github.com/viktoriavodovozova/viktoriavodozova.github.io
edit_uri: edit/main/source/docs/

# Где лежат исходные .md файлы
docs_dir: source/docs

# Куда собирать HTML (для GitHub Pages)
site_dir: site

# Тема: Material
theme:
  name: material
  palette:
    # Светлая тема по умолчанию
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    # Тёмная тема (автоматически или по клику)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  logo: assets/images/IMG_7767.jpg
  features:
    - navigation.top          # навигация сверху
    - navigation.tabs
    - navigation.sections       # подсветка в поиске
    - content.code.copy   # кнопка "копировать" в коде

  font:
    text: Roboto
    code: Fira Code

# Навигация по сайту
nav:
  - Главная: index.md
  - Лабораторные работы:
      - Создание статического сайта: labs/lab1sem2.md
      - Основы NumPy: labs/lab2sem2.md
      - CI/CD для статического сайта в SourceCraft: labs/lab3sem2.md
      - Регрессия с применением Scikit-Learn: labs/lab5sem2.md
      - Очистка и трансформация данных. Pandas: labs/lab6sem2.md
      - Анализ текста: labs/lab7sem2.md
      - Скрапинг и анализ текста: labs/lab8sem2.md
      - Работа с графикой. CI/CD. Артефакты: labs/lab9sem2.md
  - Проекты:
      - Хакатон от "Газпром нефти": projects/Proj_1.md
      - Сервис по оценке вероятности одобрения ипотеки: projects/Proj_2.md
      - Разработка нейронной сети: projects/Proj_3.md
  - Контактная информация: contact.md
# Плагины (поиск и дата последнего изменения)
plugins:
  - search


# Дополнительно: соцсети в футере
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ViktoriaVodovozova
    - icon: fontawesome/brands/telegram
      link: https://t.me/@Vvvikkktoriia


# Язык и кодировка
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details